UI_LANGUAGES = {
    'zh': {
        'main_msg': "机器人由<a href=\"https://t.me/gsyxyc\">宫水</a>打造\n\n-内置AI大模型\n-多语言切换\n-深度融合<a href=\"https://t.me/gs0z1\">宫水大世界</a>频道\n\n请选择功能：", 
        'channel_msg': "请先加入频道体验完整功能", 
        'robot_dev': "机器人开发", 
        'contact_btn': "双向", 
        'gsai': "AI", 
        'setting': "设置",
        'setting_title': "设置中心：", 
        'setting_lang': "更改语言", 
        'setting_back': "返回主菜单",
        'lang_title': "请选择界面语言 目前中文：", 
        'lang_zh': "中文", 
        'lang_en': "English", 
        'lang_back': "⬅️ 返回",
        'back_msg': "主菜单",
        'gsai_welcome': "有什么可以帮您", 
        'gsai_thinking': "🧠 正在思考...",
        'lang_sel_success': "✅ 已切换为中文界面", 
        'lang_sel_success_en': "✅ 已切换为英文界面",
        'check_channel': "请先加入频道才能使用本机器人：", 
        'join_btn': "加入频道", 
        'check_btn': "重新检测",
        
        # ===== 更新后的机器人开发标题 =====
        'dev_title': "体验最全面的机器人生态\n展示功能均能复刻/修改\n\n开发者 <a href=\"https://t.me/gsyxyc\">@gsyxyc</a>",
        'dev_captcha': "人机验证",
        # 新增 9 个默认按钮和 2 个关于按钮
        'default_2': "默认二", 'default_3': "默认三",
        'default_4': "默认四", 'default_5': "默认五", 'default_6': "默认六",
        'default_7': "默认七", 'default_8': "默认八", 'default_9': "默认九",
        'about_api': "关于api", 'about_key': "关于key",
        
        'back_dev_menu': "返回上一级",
        'captcha_title': "人机验证：",
        'captcha_math': "数学题验证",
        'correct_msg': "答对了",
        'incorrect_msg': "答错了",
        'retry_math': "重新回答",
        'exit_ai': "退出 AI 对话"
    },
    'en': {
        'main_msg': "Bot built by <a href=\"https://t.me/gsyxyc\">Gongshui</a>\n\n-Built-in AI Large Model\n-Multi-language switching\n-Deep integration with <a href=\"https://t.me/gs0z1\">Gongshui World</a> channel\n\nPlease choose a function:", 
        'channel_msg': "Please join the channel to experience the full features", 
        'robot_dev': "Bot Dev", 
        'contact_btn': "Contact", 
        'gsai': "AI", 
        'setting': "Settings",
        'setting_title': "Settings Center:", 
        'setting_lang': "Change Language", 
        'setting_back': "Back to Home",
        'lang_title': "Select interface language (Current: English):", 
        'lang_zh': "Chinese", 
        'lang_en': "English", 
        'lang_back': "⬅️ Back",
        'back_msg': "Home",
        'gsai_welcome': "How can I help you", 
        'gsai_thinking': "🧠 Thinking...",
        'lang_sel_success': "✅ Switched to Chinese", 
        'lang_sel_success_en': "✅ Switched to English",
        'check_channel': "Please join the channel first to use this bot:", 
        'join_btn': "Join Channel", 
        'check_btn': "Re-check",
        'dev_title': "Experience the most comprehensive bot ecosystem\nAll displayed features can be cloned/modified\n\nDeveloper <a href=\"https://t.me/gsyxyc\">@gsyxyc</a>",
        'dev_captcha': "Captcha",
        'default_2': "Default 2", 'default_3': "Default 3",
        'default_4': "Default 4", 'default_5': "Default 5", 'default_6': "Default 6",
        'default_7': "Default 7", 'default_8': "Default 8", 'default_9': "Default 9",
        'about_api': "About API", 'about_key': "About Key",
        'back_dev_menu': "Back",
        'captcha_title': "Captcha:",
        'captcha_math': "Math Captcha",
        'correct_msg': "Correct!",
        'incorrect_msg': "Incorrect!",
        'retry_math': "Retry",
        'exit_ai': "Exit AI"
    }
}
